[pointer]
number = { fg = "green" }
letter = { fg = "blue" }
separator = { fg = "red" }
 separator_token = "a"
x = { fg = "red" }

[[regexps]]
regular_expression = 'Started (.*)\.'
style = { fg = "red" }

[[regexps]]
regular_expression = 'Stopped .*'
style = { fg = "magenta" }
